GET http://localhost:5000/user
content-Type: application/json
X-Access-Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicGFibG9jY2MiLCJleHAiOjE2NDYzNjM4MTN9.XPkEy2FxysG6JGzPmQu4t5Fen5PI2WhFrmLapz5Jxc0
