GET http://localhost:5000/user
content-Type: application/json
x-access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjoicm9qYXNjanAiLCJleHAiOjE2NDYzMzQ4NDF9.VRO7e9swUD8Peg1es5F1D3bLyqRusdXVpmQqcuBWfJY
